augmentations:
- RandomAffine:
    degrees:
    - 0
    - 360
    p: 0.5
    scale:
    - 0.9
    - 1.1
    translate:
    - 0
    - 0.1
- RandomBrightnessContrast:
    brightness:
    - -0.1
    - 0.1
    contrast:
    - 0.8
    - 1.2
    p: 0.5
- RandomVariableGaussianBlur:
    kernel_size: 5
    p: 0.5
    sigma:
    - 0.1
    - 0.7
# - RandomVariableGaussianNoise:
#     mean:
#     - 0
#     - 0.05
#     p: 0.5
#     std:
#     - 0
#     - 0.05
# - RandomVariableElasticTransform:
#     alpha:
#     - 1
#     - 2
#     p: 0.25
#     sigma:
#     - 6
#     - 8
- RandomSharpness:
    p: 0.25
    sharpness: 5
- RandomHorizontalFlip:
    p: 0.5
- RandomVerticalFlip:
    p: 0.5
callbacks:
  epoch:
  - pylot.callbacks.PrintLogged
  - pylot.callbacks.JobProgress
  - pylot.callbacks.ETA
  - pylot.callbacks.TerminateOnNaN
  - pylot.callbacks.ModelCheckpoint:
      monitor: dice_score
      phase: val_id
  - pylot.callbacks.ModelCheckpoint:
      monitor: dice_score
      phase: val_od
  - fengepad.callbacks.WandbLogger:
      project: Dune
      entity: nicezheng-jiang-bupt #update this!
prompt_generator:
  _class: fengepad.interactions.prompt_generator.FlexiblePromptEmbed
  bbox_embed:
    _fn: fengepad.interactions.embed.bbox_shaded
  box_generators:
  - _class: fengepad.interactions.boxes.UniformBBox 
  click_embed:
    _fn: fengepad.interactions.embed.click_onehot
  init_neg_click_generators:
    - _class: fengepad.interactions.clicks.RandomClick
    - _class: fengepad.interactions.clicks.RandBorderClick
  init_pos_click_generators:
    - _class: fengepad.interactions.clicks.RandomClick
    - _class: fengepad.interactions.clicks.ComponentCenterClick
    - _class: fengepad.interactions.clicks.RandBorderClick
  scribble_generators:
    - _class: fengepad.interactions.scribbles.LineScribble
    - _class: fengepad.interactions.scribbles.CenterlineScribbleForDune
    - _class: fengepad.interactions.scribbles.ContourScribble
    - _class: fengepad.interactions.polylines.ContourPolylineForDune
    # - _class: fengepad.interactions.polylines.CenterlinePolylineForDune
  correction_click_generators:
    - _class: fengepad.interactions.clicks.RandomClick
    - _class: fengepad.interactions.clicks.ComponentCenterClick
    - _class: fengepad.interactions.clicks.RandBorderClick
  correction_clicks: [1,2]
  correction_scribbles: [1,2]
  init_pos_click: [1,2]
  init_neg_click: [0,2]
  init_neg_scribble: [0,2]
  init_pos_scribble: [1,2]
  prob_bbox: 0.5
  prob_click: 0.5
  prob_scribble: 0.5
  from_logits: true
data:
  _class: fengepad.datasets.superpixel.SuperpixelMultiDataset
  samples_per_epoch: 1000
  sampling: hierarchical
  superpixel_prob: 0.5
  train_tasks: #add your own datasets here!
    - _class: fengepad.datasets.dunedataset.Dune
      subdataset: MAO
      label: dune
  val_tasks: #add your own datasets here!
    - _class: fengepad.datasets.dunedataset.Dune
      subdataset: MAO
      label: dune
dataloader:
  batch_size: 8
  num_workers: 16
  pin_memory: true
experiment:
  seed: 42
  detach: true
  verbose: true
log:
  checkpoint_freq: 5
  metrics:
    dice_score:
      _fn: pylot.metrics.dice_score
      batch_reduction: null
      from_logits: true
    accuracy:
      _fn: pylot.metrics.accuracy
      batch_reduction: null
      from_logits: true
    mean_iou:
      _fn: pylot.metrics.mean_iou
      batch_reduction: null
      from_logits: true
  root: /home/jiangzheng/code/fengepad/output/ #update this!
  save_freq: 100
loss_func:
  _class: fengepad.loss.FocalDiceLoss
  batch_reduction: null
  from_logits: true
model:
  _class: fengepad.models.network.UNet
  features:
  - 192
  - 192
  - 192
  - 192
  in_channels: 5
  out_channels: 1
  # options used in BaseExperiment.build_model()
  pretrained_weights: null 
  compile: true
optim:
  _class: torch.optim.Adam
  lr: 0.0001
train:
  epochs: 1000
  eval_freq: 10
  prompt_iter: 5
  prompt_iter_val: 1
  bf16: true
  grad_accumulation: false
